# Generated by Django 2.2.7 on 2019-11-09 18:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit_tracker', '0002_auto_20191108_1840'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.AddField(
            model_name='habit',
            name='observer',
            field=models.ManyToManyField(blank=True, related_name='habits_observing', to=settings.AUTH_USER_MODEL),
        ),
    ]
